---
- name: Deploy EC2 Instances                  # ! It doesn't have Idempotency Property cause of amazon.aws.ec2_instance module !
  hosts: ansibleController
  vars_files:
  - ./group_vars/credentials.yml
  - ./group_vars/all.yml
  vars: 
    aws_access_key: "{{ aws_access_key }}"    # credentials from vault file
    aws_secret_key: "{{ aws_secret_key }}"   
  tasks:
    # - name: Install Dependencies - part 1
    #   apt: name={{ item }} state=present
    #   with_items:
    #    - python2                            # -> python/python2, but we neet pip/pip2
    #   become: yes
    # - name: Install Dependencies - part 2   # I did it manually because ansible didn't allow running it <- the AnsibleController already has python3
    #   command: python get-pip.py            # -> pip/pip2
    #   become: yes
    # - name: Install Dependencies - part 3   # these packages should be installed with pip2 (pip3 is not recognised by aws.ec2 module)
    #   pip: name={{ item }} state=present    # I did it manually 
    #   with_items:
    #    - boto
    #    - boto3
    #    - botocore
    #   become: yes

    - name: Upload public key to AWS
      amazon.aws.ec2_key:                     # amazon.aws needs pip boto, pip boto3, etc ; amazon.aws can't use pip3 boto 
        name: aws_instance_key_pair
        key_material: "{{ lookup('file', '{{ path }}/.ssh/aws_instance_key_pair.pub') }}"  # [added in AWS Console before]
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: eu-west-3
    
    - name: Create a new Security Group for hosts
      amazon.aws.ec2_group:
        name: Ansible
        description: ansible group
        vpc_id: vpc-0d9dca9688428eb78 
        region: eu-west-3
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:                                  # inbound rules
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp                          # allow communication between all instances: both webapp and dbserver (Private IPs)
            from_port: 80
            to_port: 80
            group_name: Ansible                 # members of this security group will get access
          - proto: icmp                         # for ping tests
            from_port: -1                       # all ports
            to_port: -1                         #
            group_name: Ansible                 
          - proto: tcp                          # dbserver sends on port 3306, so webapp server needs to allow it
            from_port: 3306
            to_port: 3306
            group_name: Ansible

    - name: Deploy EC2 - web_servers group and db_servers   
      include: tasks/create_instances.yml
      with_items:
      - { group: 'web_servers', count: '2', aws_access_key: "{{ aws_access_key }}", aws_secret_key: "{{ aws_secret_key }}"}
      - { group: 'db_servers', count: '1', aws_access_key: "{{ aws_access_key }}", aws_secret_key: "{{ aws_secret_key }}"}

      