---
- name: Deploy EC2 Instances
  hosts: ansibleController
  vars_files:
  - ./group_vars/credentials.yml
  vars: 
    aws_access_key: "{{ aws_access_key }}"    # credentials from vault file
    aws_secret_key: "{{ aws_secret_key }}"   
  tasks:
    - name: Install Dependencies
      apt: name={{ item }} state=present
      with_items:
       - python3-boto
       - python3-boto3
       - python3-botocore
       - python3

    - name: Create a new SSH ec2 key-pair
      amazon.aws.ec2_key:
        name: aws_instance_key_pair
        state: present

    - include: tasks/launch_group_ec2_instances.yml
      with_items:
      - { group: 'web_servers', count: '2', aws_access_key: "{{ aws_access_key }}", aws_secret_key: "{{ aws_secret_key }}"}
      - { group: 'db_servers', count: '1', aws_access_key: "{{ aws_access_key }}", aws_secret_key: "{{ aws_secret_key }}"}


