# In app.py there is this line:
# mysql_database_host = 'MYSQL_DATABASE_HOST' in os.environ and os.environ['MYSQL_DATABASE_HOST'] or  'localhost'
# So, we need to add the mysql server IP in that var

# Also, we have to do a full duplex communication between webapps and dbserver -> AWS Security Group
# Connect mysql server to webapp servers
#- inbound rule for webapp server <- custom http from dbserver (his ip address)

# Finally, Create a load balancer for all webapp servers

---
- name: Networking & Load balancing                 
  hosts: ansibleController
  vars_files:
  - ./group_vars/credentials.yml
  - ./group_vars/all.yml
  vars: 
    aws_access_key: "{{ aws_access_key }}"    # credentials from vault file
    aws_secret_key: "{{ aws_secret_key }}"   
  tasks:
    - 
  
  






