    - name: Launch Instances
      ec2:
        key_name: aws_instance_key_pair  # SSH Key Pair
        instance_type: t2.micro
        image: ami-0c6ebbd55ab05f070     # ubuntu server 20.04 image 64-bit Arm
        region: eu-west-3b
        group: Ansible                   # security group
        count: '{{ item.count }}'
        vpc_subnet_id: subnet-07bec51cb606cb178
        assign_public_ip: yes
        aws_access_key: "{{ item.aws_access_key }}"
        aws_secret_key: "{{ item.aws_secret_key }}"
        state: present
        wait: yes                # wait for the instance to reach its desired state before returning.
        wait_timeout: 500
        register: ec2

    - name: Add new instance into inventory
      vars:
        group: "{{ item.group }}"
      add_host:
        hostname: "{{ item.public_ip }}"
        private_ip: "{{ item.private_ip }}"
        groupname: "{{ group }}"
      loop: "{{ ec2.instances }}"